apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: podinfo
  namespace: podinfo
spec:
  sso:
    - name: PodInfo SSO
      clientId: podinfo
      redirectUris:
        - "https://podinfo.uds.dev/*"
      enableAuthserviceSelector:
        app.kubernetes.io/name: podinfo
      groups:
        anyOf:
          - "/UDS Core/Admin"

  network:
    serviceMesh:
      mode: ambient

    expose:
      - service: podinfo
        selector:
          app.kubernetes.io/name: podinfo
        host: podinfo
        gateway: tenant
        port: 9898

    allow:
      - direction: Egress
        selector:
          app.kubernetes.io/name: podinfo
        remoteGenerated: Anywhere
        port: 443