apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: uds-os
  namespace: tinkerbell
spec:
  data: |
    name: uds-os
    version: "0.1"
    global_timeout: 9800
    tasks:
      - name: "os installation"
        worker: {{`"{{.worker_id}}"`}}
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        environment:
          GLOBAL_VALUE: "my global value"
        actions:
          - name: "stream image"
            image: quay.io/tinkerbell/actions/oci2disk:latest
            timeout: 9600
            environment:
              DEST_DISK: {{`{{ index .Hardware.Disks 0 }}`}}
              IMG_URL: "us-central1-docker.pkg.dev/eddiezane-playground/canes-hw-lab/uds-os-bootable:demo-40g.gz"
              COMPRESSED: true
          - name: "add cloud-init config"
            image: quay.io/tinkerbell/actions/writefile:latest
            timeout: 90
            environment:
              CONTENTS: |
                #cloud-config
                debug: true
                hostname: {{ printf "uds-edge-os-{{`{{ trunc 4 .MachineID }}`}}" }}
                # TODO: initial auth - https://github.com/defenseunicorns/uds-edge-os/issues/50
                users:
                  - name: uds
                    passwd: $6$R96torUQvXuKYbqb$mKg0b/BngVnfjiXcp89hszhu7BgQV4btLGlf9XW0i.rrrfX4kIGZ17GsLSK1OEnyH7LLtwP4Gm6sy34hl20re1
                    groups: ["admin"]
                    # TODO: initial auth - https://github.com/defenseunicorns/uds-edge-os/issues/50
                    ssh_authorized_keys:
                      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOSDVzhukBpcGr0k/S6A6KlatLg3wactdkV8RnBAlkS canes@defenseunicorns.com
                chpasswd:
                  list: "uds:unicorn123!@#UN"
                  expire: true

                write_files:
                  - path: /etc/k0s/token
                    permissions: 0744
                    content: |
                      {{ .Values.join_token }}
                  - path: /etc/k0s/k0s.yaml
                    permissions: 0744
                    content: |
                      apiVersion: k0s.k0sproject.io/v1beta1
                      kind: Cluster
                      metadata:
                        name: k0s
                      spec:
                        network:
                          nodeLocalLoadBalancing:
                            enabled: true
                            type: EnvoyProxy

                k0s:
                  args:
                    - --enable-worker --no-taints --token-file /etc/k0s/token
                  enabled: true

                install:
                  device: auto
                  reboot: true
                  grub-entry-name: UDS Edge OS
                  auto: true

                reset:
                  grub-entry-name: UDS Edge OS Reset
                upgrade:
                  grub-entry-name: UDS Edge OS Upgrade
                  # Upgrade sizing increase to account for UDS Core
                  system:
                    size: 4680
                  passive:
                    size: 4680

                stages:
                  rootfs:
                    - name: "Libvirt mount"
                      environment_file: /run/cos/cos-layout.env
                      environment:
                        CUSTOM_BIND_MOUNTS: "/var/lib/libvirt"
                  boot:
                    - name: "Setup NTP"
                      systemctl:
                        enable:
                          - systemd-timesyncd
                      timesyncd:
                        NTP: "0.rhel.pool.ntp.org"
                        FallbackNTP: "1.rhel.pool.ntp.org"
                    - name: "Restart NTP service so it gets the new config"
                      commands:
                        - systemctl restart systemd-timesyncd
                    - name: "disable uds bootstrap"
                      commands:
                        - systemctl disable uds-bootstrap.service
                  network.before:
                    - name: Setup Network
                      files:
                        - path: /tmp/nmstate.yaml
                          permissions: 0600
                          content: |
                            interfaces:
                              - name: {{ printf "{{`{{with index .Values.network 0}}{{.name}}{{end}}`}}" }}
                                type: ethernet
                                state: up
                                ipv4:
                                  enabled: true
                                  dhcp: true
                                  auto-dns: true
                                  auto-routes: true
                                  auto-gateway: true
                                ipv6:
                                  enabled: false

                    # Remove default symlink to /run/systemd/resolve/resolv.conf which doesn't exist and point at NetworkManager resolv.conf
                    - name: Configure NetworkManager DNS
                      commands:
                        - rm -f /etc/resolv.conf
                        - ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf
                        - systemctl restart NetworkManager

                    - name: Apply network configuration
                      commands:
                        - echo "network.before test" > /tmp/network.before.log
                        - nmstatectl apply /tmp/nmstate.yaml
              DEST_DISK: {{`{{ formatPartition ( index .Hardware.Disks 0 ) 2 }}`}}
              DEST_PATH: /90_custom.yaml
              DIRMODE: "0700"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0600"
              UID: "0"
          - name: "reboot"
            image: ghcr.io/jacobweinstock/waitdaemon:latest
            timeout: 90
            pid: host
            command: ["reboot"]
            environment:
              IMAGE: alpine
              WAIT_SECONDS: 10
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
