apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: uds-os-old
  namespace: tinkerbell
spec:
  data: |
    name: uds-os-old
    version: "0.1"
    global_timeout: 9800
    tasks:
      - name: "os installation"
        worker: {{`"{{.worker_id}}"`}}
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        environment:
          GLOBAL_VALUE: "my global value"
        actions:
          - name: "stream image"
            image: quay.io/tinkerbell/actions/oci2disk:latest
            timeout: 9600
            environment:
              DEST_DISK: {{`{{ index .Hardware.Disks 0 }}`}}
              IMG_URL: "us-central1-docker.pkg.dev/eddiezane-playground/canes-hw-lab/uds-os-bootable:40g.gz"
              COMPRESSED: true
          - name: "add cloud-init config"
            image: quay.io/tinkerbell/actions/writefile:latest
            timeout: 90
            environment:
              CONTENTS: |
                #cloud-config
                debug: true
                hostname: {{ printf "uds-edge-os-{{`{{ trunc 4 .MachineID }}`}}" }}
                # TODO: initial auth - https://github.com/defenseunicorns/uds-edge-os/issues/50
                users:
                  - name: uds
                    passwd: $6$R96torUQvXuKYbqb$mKg0b/BngVnfjiXcp89hszhu7BgQV4btLGlf9XW0i.rrrfX4kIGZ17GsLSK1OEnyH7LLtwP4Gm6sy34hl20re1
                    groups: ["admin"]
                    # TODO: initial auth - https://github.com/defenseunicorns/uds-edge-os/issues/50
                    ssh_authorized_keys:
                      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOSDVzhukBpcGr0k/S6A6KlatLg3wactdkV8RnBAlkS canes@defenseunicorns.com
                chpasswd:
                  list: "uds:unicorn123!@#UN"
                  expire: true

                write_files:
                  - path: /etc/k0s/token
                    permissions: 0744
                    content: |
                      H4sIAAAAAAAC/2xVXY+rOhJ8n1+RP3DONRBmN5H24UDsJCQ4Y+M24DfAPkPAEIYw+Vrtf19N7lxpV7qSH9pdrSrLalUVw1Ga8Xw89cvZxXmp7Od5MuN5+fJj9l0vX2az2awy43T8fayKyfwoPqf6NB6n+w9dTMVytk/QtE+ckIOOxDFYcRlBAipiiAB/YmgKWydKgAcc0xVL5aAQ8RKIAoWslFYd2X3hHNZRV6wjkvYnz9iggJQPyYZsCmdoNOI8hWFfOkNUbFQjWsI5XHfMkkAjjbnUlFmyYYJIDmQuwK9jRw2prXdaDjl0t8YI8pFKHihQXryxB4mlL4D3BvuvIALKcVTzvrqa9+EvTP0vJiDqDVYfTMpQIT9lLaES80yviCql8vPOSWMy5CLjKm6lp1xNCnCCGOsVeGQTWhrlDcUAMmSSSAYYJRBhjchzNkHk8vUnALRnDWkO8nSXGR8TzPcJUkMCHKpNUBw2sbt7vLtCEKda5TuxCfK9S/O8Z56xv+Yl0kx2w7F07Zx1N5+mfNq5w0fSDzueRuEhJVklaZp7clM+7IW79Fau/TbBkygy8lmtZRiz0+2QBVOKJ6VxfE3a+CLWt63CVz/JaEjXelv0dQ6onkt3kedNNEGyuKU29qquulKPXSqYpjgLiMnqLu1ib+9tUdjYrcHxKF3yataVK7voleLIr0S9FdgBJlQUP3Rf9joHoULhqhjQP5348cuv0PstQc6gMy6rNfFMH4XSsluRbXeso61otS+7m6Id2TApA9GSN3lfHBXhLd/wOrfDW9HByNLByRFtExQ15SMSZTZEclMD4MW8JHBJV0Qmvb3L68AUqk9JL6eiD16L+2LHU53ort4JTLeip2+y4TZPeR07gReTKGINtYmIVNnyhjkSmY2es1RT1pKAuwMv2igIWyegWAexlC3faMKOCw9ABhrZkHVDADjqhVVbaJ2QpfmcQwQMeADwfhGwvXKEbzLlWDkkY20kzIZjQ/BOOlbmbY441G9lA1fpKJuntWAudoqWHFinxyqtxwIqXz+Crx188JYEAtHgS7+wlh9Wdlts6qw6TmPc4yu7nkYtLMo9khQd8bnlJ/DUQcv6LlIHmFTXvPk1GqBrbsnEH+S1tCoGLx9Zy++xiEix0q87ZxglZhfx4Dx39UfY0oJm9Vo68Zx7Wy9+vI8mU275IKe0qRu+Co4cRQ8jKJPgJEUGrrQEMbe9cLe+cDnYPJUZ6wbEuujTpHwdp3hX3acYWn9KHKUKt56XVt3M2pEKqKezYVe2N0T7wQfEbomVXQU63bmAtFV+3MBdOpGiyFntXVJDw48mnC7wa+hyoUTZxuMBuG9g8SbsgOPGBoXHj3nHDxqiCZrtHXB7lQ+bxk2AUhKxxMVu0WlbWQ68l0Ph1HvukM9U4nto6TxP5xedRudC1DSxQQbuuy+tfstbeWZd5ceC99CTkHrUK3v7wUFdJHYk76JJQ3vR6yiO3blH3cU5lryJJdvtH7QrBeVvAu2+vZmIlr0zJBOJ7ToBGkgMT1/es9O/ngZ/NuPFjMtZPU3DefnHHw76+TzOz3+4y9f53HuZzfqiM8tZi84v1amfzG36Myf+rL9z4js0nlNfjc/z8/ZZGmumH+XpNJ2nsRj+n+1zHE0//fiL6dlsj71ezsJT//v4/jKM5rcZTV+Z83L27/+8fLE+xb9J/ob+Kfx8wnRqTb+cHT8eo/fxszLV4z5vbkdneu1fB+flvwEAAP//BJSM7AMHAAA=
                  - path: /etc/k0s/k0s.yaml
                    permissions: 0744
                    content: |
                      apiVersion: k0s.k0sproject.io/v1beta1
                      kind: Cluster
                      metadata:
                        name: k0s
                      spec:
                        network:
                          nodeLocalLoadBalancing:
                            enabled: true
                            type: EnvoyProxy

                k0s-worker:
                  enabled: true
                  args:
                    - --token-file /etc/k0s/token

                install:
                  device: auto
                  reboot: true
                  grub-entry-name: UDS Edge OS
                  auto: true

                reset:
                  grub-entry-name: UDS Edge OS Reset
                upgrade:
                  grub-entry-name: UDS Edge OS Upgrade
                  # Upgrade sizing increase to account for UDS Core
                  system:
                    size: 4680
                  passive:
                    size: 4680

                stages:
                  network.before:
                    - name: Setup Dummy Network
                      files:
                        - path: /tmp/nmstate.yaml
                          permissions: 0600
                          content: |
                            interfaces:
                              - name: {{ printf "{{`{{with index .Values.network 0}}{{.name}}{{end}}`}}" }}
                                type: ethernet
                                state: up
                                ipv4:
                                  enabled: true
                                  dhcp: true
                                ipv6:
                                  enabled: false
                              - name: dummy0
                                type: dummy
                                state: up
                                ipv4:
                                  enabled: true
                                  address:
                                    - ip: 203.0.113.254
                                      prefix-length: 31
                                  dhcp: false
                                  auto-dns: false
                                  auto-routes: false
                                  auto-gateway: false
                                ipv6:
                                  enabled: false
                            routes:
                              config:
                                - destination: 0.0.0.0/0
                                  next-hop-address: 203.0.113.254
                                  next-hop-interface: dummy0
                                  metric: 1000

                    - name: Configure NetworkManager's dnsmasq for the UDS Core domain
                      files:
                        - path: /etc/NetworkManager/conf.d/dns.conf
                          content: |
                            [main]
                            dns=dnsmasq
                        - path: /etc/NetworkManager/dnsmasq.d/00-main-dns.conf
                          content: |
                            # Dummy `if` IP address
                            listen-address=203.0.113.254
                            server=1.1.1.1
                        - path: /etc/NetworkManager/dnsmasq.d/01-uds-dev.conf
                          content: |
                            address=/.admin.uds.dev/10.10.101.21
                            address=/.uds.dev/10.10.101.22
                        - path: /run/systemd/resolve/resolv.conf
                          content: |
                            # Generated by NetworkManager
                            nameserver 203.0.113.254
                            options edns0 trust-ad
                      commands:
                        - systemctl restart NetworkManager

                    - name: Apply network configuration
                      commands:
                        - echo "network.before test" > /tmp/network.before.log
                        - nmstatectl apply /tmp/nmstate.yaml
              DEST_DISK: {{`{{ formatPartition ( index .Hardware.Disks 0 ) 2 }}`}}
              DEST_PATH: /90_custom.yaml
              DIRMODE: "0700"
              FS_TYPE: ext4
              GID: "0"
              MODE: "0600"
              UID: "0"
          - name: "reboot"
            image: ghcr.io/jacobweinstock/waitdaemon:latest
            timeout: 90
            pid: host
            command: ["reboot"]
            environment:
              IMAGE: alpine
              WAIT_SECONDS: 10
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
