### This dev stack will assume k8s and the need for metallb

# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json
vars:
  stage: "roosevelt"

import:
  - catalog/_versions.yaml
  - catalog/20-zarf-init.yaml
  - catalog/30-core-base.yaml
  - catalog/40-core-identity-auth.yaml
  - catalog/50-podinfo.yaml
  - catalog/60-metal-lb.yaml
  - catalog/70-core-monitoring.yaml
  - catalog/80-uds-ui.yaml

  - secrets/decrypted/roosevelt.yaml

# Environment level overrides for this stack
components:
  terraform:
    metal-lb:
      vars:
        package_requirements:
          source: "oci://ghcr.io/uds-packages/metallb:{{.vars.metal_lb_version}}"
          package_vars:
            IP_ADDRESS_POOL: "192.168.69.200-192.168.69.220"

    core-identity-authorization:
      vars:
        package_overrides_map:
          # 1st key = UDS package component name
          # (maps to Terraform uds_package.component.name)
          keycloak:
            # 2nd key = Helm chart name inside that component
            # (maps to Terraform uds_package.component.override.chart_name)
            # It is also "keycloak" here because the component and chart share the same name.
            keycloak:
              # Non-sensitive chart values
              values:
                insecureAdminPasswordGeneration.enabled: "true"

    podinfo:
      vars:
        package_overrides_map:
          # 1st key = UDS package component name
          # (maps to Terraform uds_package.component.name)
          podinfo:
            # 2nd key = Helm chart name inside that component
            # (maps to Terraform uds_package.component.override.chart_name)
            # It is also "podinfo" here because the component and chart share the same name.
            podinfo:
              # Non-sensitive chart values
              values:
                replicaCount: 2

    uds-ui:
      vars:
        package_overrides_map:
          # 1st key = UDS package component name
          # (maps to Terraform uds_package.component.name)
          uds-ui:
            # 2nd key = Helm chart name inside that component
            # (maps to Terraform uds_package.component.override.chart_name)
            # It is also "uds-ui" here because the component and chart share the same name.
            uds-ui:
              # Non-sensitive chart values
              values:
                resources.requests.memory: "1Gi"
                resources.limits.memory: "10Gi"
                resources.requests.cpu: "100m"
                resources.limits.cpu: "4000m"
                sso.enabled: "false"
